### ISSUE TITLE
Default headers don't seem to be set on the context

### ISSUE THREAD

**Issue by janpieterz** [Particular/NServiceBus.Testing#110]
I'd expect the default NSB headers to be set when executing the following code:
```
var handler = Test.Handler<RandomHandler>(new RandomHandler()
{
    Log = logger.Object
});
handler.OnMessage(message);
```

But when executing `context.MessageHeaders[Headers.TimeSent]` I get a `System.Collections.Generic.KeyNotFoundException`.

Versions: 
- NServiceBus 6.2.0
- NServiceBus.Testing 6.0.1

**Comment by timbussmann** [comment]
yeah sadly that's not happening as the testing framework just calls the handler without executing the full pipeline (which it did in v5). But at the current point, I don't really see a nice way to provide behavior-based logic into the tests without completely writing the logic to emulate core's behavior.

Is there any reason you want to read this header value?

**Comment by janpieterz** [comment]
I imagined it would be a lot of work! Might be interesting to try and set some sane defaults? Like datetime.now, random guids? Or would that be too distracting?

We use it sometimes to determine when something happened instead of sending it as a specific parameter, easily replaced of course by a parameter but just handy as the data is anyway going over the bus already.

I've for now set this in our tests manually.

**Comment by timbussmann** [comment]
technically the framework could be adjusted to set some header values, but the challenge would be to keep the behavior correctly in sync with the behavior of NServiceBus. 

As in v5, the testing framework was executing the pipeline, it's quite reasonable to expect the same behavior in v6, but we decided to change the behavior in v6 as executing the full pipeline requires intense and complex setup which we wanted/needed to avoid (that's why we're mostly advertising the the AAA syntax nowadays). 

For tests which require the full pipeline to work, I'd rather recommend running a full endpoint as the test, but I have to admit that we do not have any tooling available which would make these kind of tests easier to write at the moment.

**Comment by janpieterz** [comment]
I'll convert these over slowly to AAA style and then set needed stuff myself there! 

Plus anyway maybe move away from using the headers, make it more an explicit bit of information.

Thanks for your comments/insights!
