### ISSUE TITLE
NSB.Testing a handler that sends/publishes several times only handle the first message

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus.Testing#18]
Hello there, despite a fix on https://github.com/Particular/NServiceBus/issues/489, Im having similar behavior on 4.7.1 (but not using the obsolete batch api):

Im using 4.7.1 and have a handler that uses a for loop and do several Bus.SendLocal inside:

[Handler]
for(int i = 0; i < 5; i++)
{
    Bus.SendLocal(cmd => { cmd.Id = id++; });
}

But the ExpectSendLocal is invoked only once. If I explicit more than one ExpectSendLocal directives, all instances are called with the first element.

Do I need to do anything different or is it a bug ?

Bruno Bertechini

**Comment by brunobertechini** [comment]
Hello @mlalevic , did you test the above code on 4.7.1 ? Or only on 5.x ?

I didn't have time to use this solution at that time, so I moved to use a Mock Bus instead.

Now Im going back to NServiceBus.Testing and I still have the same issue (still on 4.7.1). Including Bus.Publish.

I did changed my test code to your approach. Same behavior.

This is my *original* Test code :

```C#

Test.Handler<MyHandler>()
.ExpectPublish<MyEvent>(evt =>
{
    evt.Id.WillBe(1);
    return true;
})
.ExpectPublish<MyEvent>(evt =>
{
    evt.Id.WillBe(2);
    return true;
})
.OnMessage<MyMessage>();


public class MyEvent {  public int Id { get; set; } }

public class MyHandler : IHandleMessages<MyMessage>
{
        public void Handle(MyMessage message)
        {
              for (int i = 1; i <= 2; i++)
            {
                Bus.Publish<MyEvent>(evt => 
                {
                    evt.Id = i;
                });
            }
        }
}
```

And this is the new code using your approach:

```C#
    var handlerUnderTest = Test.Handler<MyHandler>();

    handlerUnderTest.ExpectPublish<MyEvent>(evt =>
                {
                    evt.Id.WillBe(1);
                    return true;
                });

    handlerUnderTest.ExpectPublish<MyEvent>(evt =>
                {
                    evt.Id.WillBe(2);
                    return true;
                });

    handlerUnderTest.OnMessage<MyMessage>();

```

Im still not able to use NServiceBus.Testing when I have multiple Bus.Publish or Bus.Send;SendLocal .

Note: Both 'ExpectPublish' are called, but with the same instance of evt (the first one).

Any idea?

Bruno Bertechini

**Comment by mlalevic** [comment]
Try this:
```c#
    var handlerUnderTest = Test.Handler<MyHandler>();

    handlerUnderTest.ExpectPublish<MyEvent>(evt =>
                {
                    if(evt.Id != 1){
                         return false;
                    }
                    return true;
                });

    handlerUnderTest.ExpectPublish<MyEvent>(evt =>
                {
                    if(evt.Id != 2){
                         return false;
                    }
                    return true;
                });

    handlerUnderTest.OnMessage<MyMessage>();
```
I'm guessing that evt.Id.WillBe(1) is assertion and this would throw exception. If I remember correctly, for each message both expectations will be tested and at least one needs to return true to satisfy the expectation. So event with id 2 will check expectation with evt.Id.WillBe(1) and will fail on assertion without reaching the second check.

**Comment by brunobertechini** [comment]
I will give it a try. Thanks @mlalevic .

So If I understand correctly, both expectations (ExpectPublish) will be called for each event published.

So for my code, it will run 4 times. But its not reaching there because the WillBe (which is an Assert) is throwing an exception.

Good. Makes sense.

I will change it and let you know.

Thanks

Bruno

**Comment by brunobertechini** [comment]
Hi @mlalevic . Just tried the code but the behavior does not work as expected. Althought I can move forward now, just wanted to clarify my findings:

Running your last sample, only the second expectation is called twice. Is it because the first expectation was correct and returned true ?

I saw that the first event being published was handled by the first expectation and everything was ok, so return true. This same event was handled by the second expectation and the return was false.

The second event published was NOT handled by the first expectation. But only for the second one. With the correct values now.

This is okay for me so I can insert both events in a List<MyEvent> and assert later. This will work just fine.

I just want to make sure this is the expected behavior and why...Is it because if one expectation already returned true it will not be called again ?

Regards

Bruno
