### ISSUE TITLE
ExpectSend delegate called with same message multiple times

### ISSUE THREAD

**Issue by dave-kennedy** [Particular/NServiceBus.Testing#30]
My saga receives a message and then publishes six commands. In my test, I'm trying to add each command to a list like so:

    var runAlertsCommands = new List<RunAlertsCommand>();

    Test.Saga(alertBatchSaga)
        .ExpectSend<RunAlertsCommand>(c => { runAlertsCommands.Add(c); return true; })
        .ExpectSend<RunAlertsCommand>(c => { runAlertsCommands.Add(c); return true; })
        .ExpectSend<RunAlertsCommand>(c => { runAlertsCommands.Add(c); return true; })
        .ExpectSend<RunAlertsCommand>(c => { runAlertsCommands.Add(c); return true; })
        .ExpectSend<RunAlertsCommand>(c => { runAlertsCommands.Add(c); return true; })
        .ExpectSend<RunAlertsCommand>(c => { runAlertsCommands.Add(c); return true; })
        .When(s => s.Handle(startAlertBatch));

The problem is at the end of the test `runAlertsCommands` contains the same message six times, instead of six different messages. I can verify by stepping through the code that six separate messages are put on the bus.

It seems that `ExpectSend` can be called however many times and the test will still pass. e.g., the following passes even though I'm only putting six messages on the bus:

    var commands = 0;

    Test.Saga(alertBatchSaga)
        .ExpectSend<RunAlertsCommand>(c => { commands++; return true; })
        .ExpectSend<RunAlertsCommand>(c => { commands++; return true; })
        .ExpectSend<RunAlertsCommand>(c => { commands++; return true; })
        .ExpectSend<RunAlertsCommand>(c => { commands++; return true; })
        .ExpectSend<RunAlertsCommand>(c => { commands++; return true; })
        .ExpectSend<RunAlertsCommand>(c => { commands++; return true; })
        .ExpectSend<RunAlertsCommand>(c => { commands++; return true; })
        .ExpectSend<RunAlertsCommand>(c => { commands++; return true; })
        .ExpectSend<RunAlertsCommand>(c => { commands++; return true; })
        .ExpectSend<RunAlertsCommand>(c => { commands++; return true; })
        .ExpectSend<RunAlertsCommand>(c => { commands++; return true; })
        .ExpectSend<RunAlertsCommand>(c => { commands++; return true; })
        .When(s => s.Handle(startAlertBatch));

**Comment by WilliamBZA** [comment]
@dave-kennedy Can you please post your alertBatchSaga code, specifically around the `Handle(startAlertBatch)` method?  It seems like you're trying to test that a message is sent a specific number of times. The `check` function passed into the `ExpectSend` method will simply add another instance of the `Func<T, bool>` you pass through and execute that for each message passed. Since the `Func<T, bool>` you're using simply adds the received command to the `runAlertsCommand` list, calling ExpectSend 6 times will add 6 of the same instance of the `c` command in each method.

Currently the testing code only runs the `check` for each type until the first one returns true. We can change this to run all of the `check`'s, and validate if one or more of them pass (PR is currently awaiting review https://github.com/Particular/NServiceBus.Testing/pull/31).

This will then allow you to write the test to check how many times a type is sent as follows:

```
Test.Saga(alertBatchSaga)
    .ExpectSend<RunAlertsCommand>(c => { return true; } )
    .When(s => s.Handle(startAlertBatch));

Assert.That(() => runAlertsCommands.Count, Is.EqualTo(6));
```

Would that help solve your issue?

**Comment by dave-kennedy** [comment]
I think that would solve the issue.

The code is nothing special:

```c#
public void Handle(StartAlertBatch msg)
{
    // get list of alerts...

    for (var i = 0; i < alerts.Count; i ++)
    {
        var runAlertsCommand = new RunAlertsCommand
        {
            AlertID = alert.ID,
        };

        Bus.Send(runAlertsCommand);
    }
}
```

**Comment by WilliamBZA** [comment]
Yeah that should work with the test sample above.

Can you update your NServiceBus.Testing package to `5.1.1` and let me know if it helps?

**Comment by dave-kennedy** [comment]
Looks good. Thanks!
